import base64
import os

def encode_file_to_py(input_file, output_file, var_name):
    """
    将文件编码为base64并保存到Python文件中
    
    Args:
        input_file: 输入文件路径
        output_file: 输出Python文件路径
        var_name: 变量名
    """
    try:
        # 读取文件并编码为base64
        with open(input_file, 'rb') as f:
            encoded_content = base64.b64encode(f.read()).decode('utf-8')
        
        # 创建Python文件内容
        lines = []
        lines.append('import base64')
        lines.append('')
        lines.append('# Base64 encoded icon')
        lines.append('# Generated by encode_icon.py')
        lines.append('')
        lines.append(f'{var_name} = """')
        lines.append(encoded_content)
        lines.append('"""')
        lines.append('')
        
        # 获取输出目录
        output_dir = os.path.dirname(output_file)
        # 如果输出目录不是空字符串，则创建目录
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
        
        # 写入输出文件
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        
        print(f"Successfully encoded {input_file} to {output_file}")
        print(f"Variable name: {var_name}")
        
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    # 编码icon.ico到icon.py
    encode_file_to_py('icon.ico', 'icon.py', 'ICON_ICO')
